# Generated by Django 5.0.6 on 2024-07-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel1',
            name='H_image',
            field=models.ImageField(default=1, upload_to='Hotel_Image'),
            preserve_default=False,
        ),
    ]
