# Generated by Django 5.0.6 on 2024-07-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one', '0009_review_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
    ]
