# Generated by Django 5.0.6 on 2024-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one', '0010_remove_review_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='reviewimage'),
        ),
    ]
